use_frameworks!

platform :ios, '10.0'

target 'ZYFTextView_Example' do
  pod 'ZYFTextView', :path => '../'

  pod 'SnapKit'
  
  target 'ZYFTextView_Tests' do
    inherit! :search_paths

    
  end
end
